export const API_URL = "http://localhost:8888"
export const AUTH_URL = API_URL + "/auth"
export const USER_URL = API_URL + "/user"
export const IMAGE_URL = API_URL + "/image"
export const LISTING_URL = API_URL + "/listing"
export const NOTIFICATION_URL = API_URL + "/notification"
